dist: bionic

language: bash

services:
- docker

addons:
    apt:
      packages:
      - wget

env:
    global:
        - CONTAINER="jrromb/img-bakery"

script:
  - set -e # less forgiving
  - echo "BUILDING $CONTAINER"
  - | 
    docker build -t $CONTAINER .
<<<<<<< HEAD
=======
    docker build -t $CONTAINER .
>>>>>>> 3b41383a2c74ad895d19c7d1b683aecaa74bdfea
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $CONTAINER
    docker logout
    wget https://raw.githubusercontent.com/jrrombaldo/containers/master/update_dockerhub_desc.sh
<<<<<<< HEAD
  
    sh ./update_dockerhub_desc.sh
=======
    ./update_dockerhub_desc.sh
>>>>>>> 3b41383a2c74ad895d19c7d1b683aecaa74bdfea
