dist: bionic
services:
- docker
language: bash
env:
    global:
        - IMG_NAME="jrromb/img-bakery"


script:
  - set -e # less forgiving
  - echo "BUILDING $CONTAINER"
  - | 
    docker build -t $IMG_NAME .
    docker build -t $CONTAINER:latest .
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $CONTAINER:latest
    docker logout
    wget https://raw.githubusercontent.com/jrrombaldo/containers/master/update_dockerhub_desc.sh
    export CONTAINER=${IMG_NAME} && ./update_dockerhub_desc.sh
