name: Build & Push 

on: [push]

jobs:
  build_Push:
    runs-on: ubuntu-latest
    
    env:
      IMG_NAME: "jrromb/img-bakery" 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker Image
      run: |
        export IMG_TAG=$(date +'%Y%m%d-%H%M')
        docker build . --file Dockerfile --tag $IMG_NAME:$IMG_TAG
        
    - name: Push to Docker Registry
      run: |
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker tag $IMG_NAME:$IMG_TAG $IMG_NAME:latest
        docker push $IMG_NAME
        docker logout
        
    # - name: Update DockerHub Description
    #   run: |
    #     wget https://raw.githubusercontent.com/jrrombaldo/containers/master/update_dockerhub_desc.sh
    #     chmod +x ./update_dockerhub_desc.sh
    #     ./update_dockerhub_desc.sh
    #   env:
    #     CONTAINER: ${IMG_NAME}



