name: Build & Push 

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag IMG_NAME:$(date +'%Y%m%d-%H%M')
      env:
        IMG_NAME: "jrromb/img-bakery" 
        IMG_TAG: $(date +'%Y%m%d-%H%M')
