name: images pipeline

on: [push]

jobs:
    docker_push:
        runs-on: ubuntu-latest
        env:
            IMG_NAME: "jrromb/img-bakery"
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        steps:
        - uses: actions/checkout@v1

        - name: Build and Push Docker Image
          run: |
            IMG_TAG=$(date +'%Y%m%d-%H%M')
            cd ./docker
            docker build . --file Dockerfile --tag $IMG_NAME:$IMG_TAG
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker tag $IMG_NAME:$IMG_TAG $IMG_NAME:latest
            docker images
            docker push $IMG_NAME
            docker logout
            rm -rf ~/.docker/config.json

        # - name: Update DockerHub Description
        #   run: |
        #     wget https://raw.githubusercontent.com/jrrombaldo/containers/master/update_dockerhub_desc.sh
        #     chmod +x ./update_dockerhub_desc.sh
        #     ./update_dockerhub_desc.sh
        #   env:
        #     CONTAINER: ${IMG_NAME}


    build_raspbian:
      name: build raspbian image
      runs-on: ubuntu-latest
      needs: [docker_push]

      env:
          IMG_URL: "https://downloads.raspberrypi.org/raspbian_lite_latest"

      steps:
      - uses: actions/checkout@v1

      - name: create raspbian image
        run: |
          sudo apt clean && sudo apt update && sudo apt install qemu-user-static
          ./build.sh
          sudo mv ./result/baked-*.img.zip ./raspbian.img.zip  && sudo chmod +r ./raspbian.img.zip

      - name: upload raspbian image
        uses: actions/upload-artifact@v1
        with:
          name: raspbian
          path: raspbian.img.zip


    build_ubuntu:
      name: build ubuntu image
      runs-on: ubuntu-latest
      needs: [docker_push]
      env:
          IMG_URL: "https://cdimage.ubuntu.com/releases/20.04.2/release/ubuntu-20.04.2-preinstalled-server-arm64+raspi.img.xz"

      steps:
      - uses: actions/checkout@v1

      - name: create ubuntu image
        run: |
          sudo apt clean && sudo apt update && sudo apt install qemu-user-static
          ./build.sh
          sudo mv ./result/baked-*.img.zip ./ubuntu.img.zip  && sudo chmod +r ./ubuntu.img.zip

      - name: upload ubuntu image
        uses: actions/upload-artifact@v1
        with:
          name: ubuntu
          path: ubuntu.img.zip


    release_images:
      name: creating release for images
      runs-on: ubuntu-latest
      needs: [build_ubuntu, build_raspbian]
      strategy:
        fail-fast: false

      steps:
        - name: download raspbian image
          uses: actions/download-artifact@v1
          with:
            name: raspbian

        - name: download ubuntu image
          uses: actions/download-artifact@v1
          with:
            name: ubuntu

        - name: create release
          uses: actions/create-release@v1
          id: create_release
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: ${{ github.run_number }}
              release_name: Release ${{ github.run_number }}
              draft: false
              prerelease: false
              body: |
                Montly release of customised raspbian and ubuntu images

        - name: upload raspbian image
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./raspbian/raspbian.img.zip
              asset_name: raspbian.img.zip
              asset_content_type: application/zip

        - name: upload ubuntu image
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./ubuntu/ubuntu.img.zip
              asset_name: ubuntu.img.zip
              asset_content_type: application/zip
